name: PythonEnv
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.9
  - pip=23.1.2
  - numpy=1.23.5
  - pandas=2.0.2
  - matplotlib=3.7.1
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - jupyter=1.0.0
  - notebook=6.5.4
  - ipywidgets=8.0.6
  - ipykernel=6.23.1
  - statsmodels=0.14.0
  - h5py=3.8.0
  - networkx=3.1
  - tqdm=4.65.0
  - numba=0.57.0
  - numexpr=2.8.4
  - pytest=7.3.1
  - pillow=9.5.0
  - biopython=1.81
  - openpyxl=3.1.2
  - xlrd=2.0.1
  - sphinx=7.0.1
  - beautifulsoup4=4.12.2
  - requests=2.31.0
  - flask=2.3.2
  - sqlalchemy=2.0.15
  - pyyaml=6.0
  - six=1.16.0
  - cython=0.29.35
  - pip:
    - anndata==0.9.1
    - scanpy==1.9.3
    - torch==2.0.1
    - torchvision==0.15.2
    - tensorflow==2.12.0
    - keras==2.12.0
    - tensorboard==2.12.3
    - umap-learn==0.5.3
    - pytest-cov==4.1.0
    - black==23.3.0
    - isort==5.12.0
    - flake8==6.0.0
    - mypy==1.3.0
    - django==4.2.2
    - fastapi==0.97.0
    - uvicorn==0.22.0
    - plotly==5.14.1
    - dash==2.10.2
    - streamlit==1.23.1
    - altair==5.0.1
    - bokeh==3.1.1
    - folium==0.14.0
    - geopandas==0.13.2
    - scikit-image==0.20.0
    - opencv-python==4.7.0.72
    - xgboost==1.7.5
    - lightgbm==3.3.5
    - catboost==1.2
    - shap==0.41.0
    - mlflow==2.4.1
    - optuna==3.2.0
    - transformers==4.30.2
    - spacy==3.5.3
    - nltk==3.8.1
    - gensim==4.3.1
    - sentence-transformers==2.2.2
    - pyarrow==12.0.1
    - dask==2023.5.1
    - ray==2.5.0
    - pyspark==3.4.1
    - boto3==1.26.160
    - pygame==2.5.0
    - gym==0.26.2
    - pydantic==1.10.9
    - pytest-benchmark==4.0.0
    - jupyterlab==4.0.1
    - nbconvert==7.4.0
    - nbformat==5.9.0
    - jupytext==1.14.5
    - penaltyblog